# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='even_connect.g2.common',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63ommon.proto\x12\x16\x65ven_connect.g2.common*\xf2\x01\n\neErrorCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x07\n\x03\x43RC\x10\x01\x12\x0c\n\x08PKT_LOST\x10\x02\x12\x0b\n\x07TIMEOUT\x10\x03\x12\x10\n\x0cNO_RESOURCES\x10\x04\x12\x0c\n\x08PB_ERROR\x10\x05\x12\x08\n\x04NULL\x10\x06\x12\x08\n\x04\x46\x41IL\x10\x07\x12\x0f\n\x0bNOT_SUPPORT\x10\x08\x12\x0b\n\x07SUPPORT\x10\t\x12\x0b\n\x07HEAD_ID\x10\n\x12\x12\n\x0eINVALID_LENGTH\x10\x0b\x12\x10\n\x0cINVALID_SDID\x10\x0c\x12\x14\n\x10\x44UPLICATE_PACKET\x10\r\x12\x18\n\x14RING_CONNECT_TIMEOUT\x10Zb\x06proto3'
)

_EERRORCODE = _descriptor.EnumDescriptor(
  name='eErrorCode',
  full_name='even_connect.g2.common.eErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CRC', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PKT_LOST', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TIMEOUT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NO_RESOURCES', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PB_ERROR', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NULL', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOT_SUPPORT', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUPPORT', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HEAD_ID', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INVALID_LENGTH', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INVALID_SDID', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DUPLICATE_PACKET', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RING_CONNECT_TIMEOUT', index=14, number=90,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=41,
  serialized_end=283,
)
_sym_db.RegisterEnumDescriptor(_EERRORCODE)

eErrorCode = enum_type_wrapper.EnumTypeWrapper(_EERRORCODE)
SUCCESS = 0
CRC = 1
PKT_LOST = 2
TIMEOUT = 3
NO_RESOURCES = 4
PB_ERROR = 5
NULL = 6
FAIL = 7
NOT_SUPPORT = 8
SUPPORT = 9
HEAD_ID = 10
INVALID_LENGTH = 11
INVALID_SDID = 12
DUPLICATE_PACKET = 13
RING_CONNECT_TIMEOUT = 90


DESCRIPTOR.enum_types_by_name['eErrorCode'] = _EERRORCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
