# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dev_settings.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dev_settings.proto',
  package='even_connect.g2.dev_settings',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x64\x65v_settings.proto\x12\x1c\x65ven_connect.g2.dev_settings\x1a\x0c\x63ommon.proto\"\x84\x01\n\nAudControl\x12\x32\n\x03\x63md\x18\x01 \x01(\x0e\x32%.even_connect.g2.dev_settings.eAudCmd\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12\x32\n\x06result\x18\x03 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"c\n\x08TimeSync\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x10\n\x08timezone\x18\x02 \x01(\x03\x12\x32\n\x06result\x18\x03 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"G\n\x11\x42\x61seConnHeartBeat\x12\x32\n\x06result\x18\x01 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"B\n\x0cQuickRestart\x12\x32\n\x06result\x18\x01 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"D\n\x0eRestoreFactory\x12\x32\n\x06result\x18\x01 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode*g\n\x07\x65\x41udCmd\x12\x10\n\x0c\x41UD_CMD_NONE\x10\x00\x12\x10\n\x0c\x41UD_CMD_OPEN\x10\x01\x12\x11\n\rAUD_CMD_CLOSE\x10\x02\x12\x11\n\rAUD_CMD_PAUSE\x10\x03\x12\x12\n\x0e\x41UD_CMD_RESUME\x10\x04\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_EAUDCMD = _descriptor.EnumDescriptor(
  name='eAudCmd',
  full_name='even_connect.g2.dev_settings.eAudCmd',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUD_CMD_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUD_CMD_OPEN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUD_CMD_CLOSE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUD_CMD_PAUSE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUD_CMD_RESUME', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=513,
  serialized_end=616,
)
_sym_db.RegisterEnumDescriptor(_EAUDCMD)

eAudCmd = enum_type_wrapper.EnumTypeWrapper(_EAUDCMD)
AUD_CMD_NONE = 0
AUD_CMD_OPEN = 1
AUD_CMD_CLOSE = 2
AUD_CMD_PAUSE = 3
AUD_CMD_RESUME = 4



_AUDCONTROL = _descriptor.Descriptor(
  name='AudControl',
  full_name='even_connect.g2.dev_settings.AudControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='even_connect.g2.dev_settings.AudControl.cmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='even_connect.g2.dev_settings.AudControl.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='even_connect.g2.dev_settings.AudControl.result', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=199,
)


_TIMESYNC = _descriptor.Descriptor(
  name='TimeSync',
  full_name='even_connect.g2.dev_settings.TimeSync',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='even_connect.g2.dev_settings.TimeSync.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timezone', full_name='even_connect.g2.dev_settings.TimeSync.timezone', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='even_connect.g2.dev_settings.TimeSync.result', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=300,
)


_BASECONNHEARTBEAT = _descriptor.Descriptor(
  name='BaseConnHeartBeat',
  full_name='even_connect.g2.dev_settings.BaseConnHeartBeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='even_connect.g2.dev_settings.BaseConnHeartBeat.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=373,
)


_QUICKRESTART = _descriptor.Descriptor(
  name='QuickRestart',
  full_name='even_connect.g2.dev_settings.QuickRestart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='even_connect.g2.dev_settings.QuickRestart.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=441,
)


_RESTOREFACTORY = _descriptor.Descriptor(
  name='RestoreFactory',
  full_name='even_connect.g2.dev_settings.RestoreFactory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='even_connect.g2.dev_settings.RestoreFactory.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=511,
)

_AUDCONTROL.fields_by_name['cmd'].enum_type = _EAUDCMD
_AUDCONTROL.fields_by_name['result'].enum_type = common__pb2._EERRORCODE
_TIMESYNC.fields_by_name['result'].enum_type = common__pb2._EERRORCODE
_BASECONNHEARTBEAT.fields_by_name['result'].enum_type = common__pb2._EERRORCODE
_QUICKRESTART.fields_by_name['result'].enum_type = common__pb2._EERRORCODE
_RESTOREFACTORY.fields_by_name['result'].enum_type = common__pb2._EERRORCODE
DESCRIPTOR.message_types_by_name['AudControl'] = _AUDCONTROL
DESCRIPTOR.message_types_by_name['TimeSync'] = _TIMESYNC
DESCRIPTOR.message_types_by_name['BaseConnHeartBeat'] = _BASECONNHEARTBEAT
DESCRIPTOR.message_types_by_name['QuickRestart'] = _QUICKRESTART
DESCRIPTOR.message_types_by_name['RestoreFactory'] = _RESTOREFACTORY
DESCRIPTOR.enum_types_by_name['eAudCmd'] = _EAUDCMD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AudControl = _reflection.GeneratedProtocolMessageType('AudControl', (_message.Message,), {
  'DESCRIPTOR' : _AUDCONTROL,
  '__module__' : 'dev_settings_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.dev_settings.AudControl)
  })
_sym_db.RegisterMessage(AudControl)

TimeSync = _reflection.GeneratedProtocolMessageType('TimeSync', (_message.Message,), {
  'DESCRIPTOR' : _TIMESYNC,
  '__module__' : 'dev_settings_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.dev_settings.TimeSync)
  })
_sym_db.RegisterMessage(TimeSync)

BaseConnHeartBeat = _reflection.GeneratedProtocolMessageType('BaseConnHeartBeat', (_message.Message,), {
  'DESCRIPTOR' : _BASECONNHEARTBEAT,
  '__module__' : 'dev_settings_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.dev_settings.BaseConnHeartBeat)
  })
_sym_db.RegisterMessage(BaseConnHeartBeat)

QuickRestart = _reflection.GeneratedProtocolMessageType('QuickRestart', (_message.Message,), {
  'DESCRIPTOR' : _QUICKRESTART,
  '__module__' : 'dev_settings_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.dev_settings.QuickRestart)
  })
_sym_db.RegisterMessage(QuickRestart)

RestoreFactory = _reflection.GeneratedProtocolMessageType('RestoreFactory', (_message.Message,), {
  'DESCRIPTOR' : _RESTOREFACTORY,
  '__module__' : 'dev_settings_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.dev_settings.RestoreFactory)
  })
_sym_db.RegisterMessage(RestoreFactory)


# @@protoc_insertion_point(module_scope)
