# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: efs_transmit.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='efs_transmit.proto',
  package='even_connect.g2.efs_transmit',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x65\x66s_transmit.proto\x12\x1c\x65ven_connect.g2.efs_transmit*k\n\x14\x65\x45venFileServiceType\x12\x1f\n\x1bNOTIFICATION_JSON_WHITELIST\x10\x00\x12!\n\x1d\x41NDROID_MSG_JSON_NOTIFICATION\x10\x01\x12\x0f\n\nOTHER_FILE\x10\xaa\x01*\xc8\x02\n\x13\x65\x45venFileServiceRsp\x12!\n\x1d\x45VEN_FILE_SERVICE_RSP_SUCCESS\x10\x00\x12#\n\x1f\x45VEN_FILE_SERVICE_RSP_START_ERR\x10\x01\x12&\n\"EVEN_FILE_SERVICE_RSP_DATA_CRC_ERR\x10\x02\x12)\n%EVEN_FILE_SERVICE_RSP_FLASH_WRITE_ERR\x10\x03\x12!\n\x1d\x45VEN_FILE_SERVICE_RSP_TIMEOUT\x10\x04\x12&\n\"EVEN_FILE_SERVICE_RSP_NO_RESOURCES\x10\x05\x12+\n\'EVEN_FILE_SERVICE_RSP_RESULT_CHECK_FAIL\x10\x06\x12\x1e\n\x1a\x45VEN_FILE_SERVICE_RSP_FAIL\x10\x07*\x99\x01\n\x19\x65\x45venFileExportServiceCID\x12&\n\"EVEN_FILE_SERVICE_CMD_EXPORT_START\x10\x00\x12%\n!EVEN_FILE_SERVICE_CMD_EXPORT_DATA\x10\x01\x12-\n)EVEN_FILE_SERVICE_CMD_EXPORT_RESULT_CHECK\x10\x02*\x91\x01\n\x17\x65\x45venFileSendServiceCID\x12$\n EVEN_FILE_SERVICE_CMD_SEND_START\x10\x00\x12#\n\x1f\x45VEN_FILE_SERVICE_CMD_SEND_DATA\x10\x01\x12+\n\'EVEN_FILE_SERVICE_CMD_SEND_RESULT_CHECK\x10\x02\x62\x06proto3'
)

_EEVENFILESERVICETYPE = _descriptor.EnumDescriptor(
  name='eEvenFileServiceType',
  full_name='even_connect.g2.efs_transmit.eEvenFileServiceType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOTIFICATION_JSON_WHITELIST', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ANDROID_MSG_JSON_NOTIFICATION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTHER_FILE', index=2, number=170,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=52,
  serialized_end=159,
)
_sym_db.RegisterEnumDescriptor(_EEVENFILESERVICETYPE)

eEvenFileServiceType = enum_type_wrapper.EnumTypeWrapper(_EEVENFILESERVICETYPE)
_EEVENFILESERVICERSP = _descriptor.EnumDescriptor(
  name='eEvenFileServiceRsp',
  full_name='even_connect.g2.efs_transmit.eEvenFileServiceRsp',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EVEN_FILE_SERVICE_RSP_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVEN_FILE_SERVICE_RSP_START_ERR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVEN_FILE_SERVICE_RSP_DATA_CRC_ERR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVEN_FILE_SERVICE_RSP_FLASH_WRITE_ERR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVEN_FILE_SERVICE_RSP_TIMEOUT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVEN_FILE_SERVICE_RSP_NO_RESOURCES', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVEN_FILE_SERVICE_RSP_RESULT_CHECK_FAIL', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVEN_FILE_SERVICE_RSP_FAIL', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=162,
  serialized_end=490,
)
_sym_db.RegisterEnumDescriptor(_EEVENFILESERVICERSP)

eEvenFileServiceRsp = enum_type_wrapper.EnumTypeWrapper(_EEVENFILESERVICERSP)
_EEVENFILEEXPORTSERVICECID = _descriptor.EnumDescriptor(
  name='eEvenFileExportServiceCID',
  full_name='even_connect.g2.efs_transmit.eEvenFileExportServiceCID',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EVEN_FILE_SERVICE_CMD_EXPORT_START', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVEN_FILE_SERVICE_CMD_EXPORT_DATA', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVEN_FILE_SERVICE_CMD_EXPORT_RESULT_CHECK', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=493,
  serialized_end=646,
)
_sym_db.RegisterEnumDescriptor(_EEVENFILEEXPORTSERVICECID)

eEvenFileExportServiceCID = enum_type_wrapper.EnumTypeWrapper(_EEVENFILEEXPORTSERVICECID)
_EEVENFILESENDSERVICECID = _descriptor.EnumDescriptor(
  name='eEvenFileSendServiceCID',
  full_name='even_connect.g2.efs_transmit.eEvenFileSendServiceCID',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EVEN_FILE_SERVICE_CMD_SEND_START', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVEN_FILE_SERVICE_CMD_SEND_DATA', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVEN_FILE_SERVICE_CMD_SEND_RESULT_CHECK', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=649,
  serialized_end=794,
)
_sym_db.RegisterEnumDescriptor(_EEVENFILESENDSERVICECID)

eEvenFileSendServiceCID = enum_type_wrapper.EnumTypeWrapper(_EEVENFILESENDSERVICECID)
NOTIFICATION_JSON_WHITELIST = 0
ANDROID_MSG_JSON_NOTIFICATION = 1
OTHER_FILE = 170
EVEN_FILE_SERVICE_RSP_SUCCESS = 0
EVEN_FILE_SERVICE_RSP_START_ERR = 1
EVEN_FILE_SERVICE_RSP_DATA_CRC_ERR = 2
EVEN_FILE_SERVICE_RSP_FLASH_WRITE_ERR = 3
EVEN_FILE_SERVICE_RSP_TIMEOUT = 4
EVEN_FILE_SERVICE_RSP_NO_RESOURCES = 5
EVEN_FILE_SERVICE_RSP_RESULT_CHECK_FAIL = 6
EVEN_FILE_SERVICE_RSP_FAIL = 7
EVEN_FILE_SERVICE_CMD_EXPORT_START = 0
EVEN_FILE_SERVICE_CMD_EXPORT_DATA = 1
EVEN_FILE_SERVICE_CMD_EXPORT_RESULT_CHECK = 2
EVEN_FILE_SERVICE_CMD_SEND_START = 0
EVEN_FILE_SERVICE_CMD_SEND_DATA = 1
EVEN_FILE_SERVICE_CMD_SEND_RESULT_CHECK = 2


DESCRIPTOR.enum_types_by_name['eEvenFileServiceType'] = _EEVENFILESERVICETYPE
DESCRIPTOR.enum_types_by_name['eEvenFileServiceRsp'] = _EEVENFILESERVICERSP
DESCRIPTOR.enum_types_by_name['eEvenFileExportServiceCID'] = _EEVENFILEEXPORTSERVICECID
DESCRIPTOR.enum_types_by_name['eEvenFileSendServiceCID'] = _EEVENFILESENDSERVICECID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
