# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: glasses_case.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='glasses_case.proto',
  package='even_connect.g2.glasses_case',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12glasses_case.proto\x12\x1c\x65ven_connect.g2.glasses_case\x1a\x0c\x63ommon.proto\"\x94\x01\n\x0fGlassesCaseInfo\x12\x0b\n\x03soc\x18\x01 \x01(\x05\x12\x14\n\x0c\x63hargeStatus\x18\x02 \x01(\x05\x12\x11\n\tlidStatus\x18\x03 \x01(\x05\x12\x14\n\x0cinCaseStatus\x18\x04 \x01(\x05\x12\x35\n\terrorCode\x18\x05 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"\xc8\x01\n\x16GlassesCaseDataPackage\x12\x46\n\tcommandId\x18\x01 \x01(\x0e\x32\x33.even_connect.g2.glasses_case.eGlassesCaseCommandId\x12\x13\n\x0bmagicRandom\x18\x02 \x01(\x05\x12\x44\n\x08\x63\x61seInfo\x18\x03 \x01(\x0b\x32-.even_connect.g2.glasses_case.GlassesCaseInfoH\x00\x88\x01\x01\x42\x0b\n\t_caseInfo*8\n\x15\x65GlassesCaseCommandId\x12\x10\n\x0cNONE_COMMAND\x10\x00\x12\r\n\tCASE_INFO\x10\x01\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_EGLASSESCASECOMMANDID = _descriptor.EnumDescriptor(
  name='eGlassesCaseCommandId',
  full_name='even_connect.g2.glasses_case.eGlassesCaseCommandId',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE_COMMAND', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CASE_INFO', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=420,
  serialized_end=476,
)
_sym_db.RegisterEnumDescriptor(_EGLASSESCASECOMMANDID)

eGlassesCaseCommandId = enum_type_wrapper.EnumTypeWrapper(_EGLASSESCASECOMMANDID)
NONE_COMMAND = 0
CASE_INFO = 1



_GLASSESCASEINFO = _descriptor.Descriptor(
  name='GlassesCaseInfo',
  full_name='even_connect.g2.glasses_case.GlassesCaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='soc', full_name='even_connect.g2.glasses_case.GlassesCaseInfo.soc', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chargeStatus', full_name='even_connect.g2.glasses_case.GlassesCaseInfo.chargeStatus', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lidStatus', full_name='even_connect.g2.glasses_case.GlassesCaseInfo.lidStatus', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inCaseStatus', full_name='even_connect.g2.glasses_case.GlassesCaseInfo.inCaseStatus', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='even_connect.g2.glasses_case.GlassesCaseInfo.errorCode', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=215,
)


_GLASSESCASEDATAPACKAGE = _descriptor.Descriptor(
  name='GlassesCaseDataPackage',
  full_name='even_connect.g2.glasses_case.GlassesCaseDataPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='commandId', full_name='even_connect.g2.glasses_case.GlassesCaseDataPackage.commandId', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='magicRandom', full_name='even_connect.g2.glasses_case.GlassesCaseDataPackage.magicRandom', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='caseInfo', full_name='even_connect.g2.glasses_case.GlassesCaseDataPackage.caseInfo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_caseInfo', full_name='even_connect.g2.glasses_case.GlassesCaseDataPackage._caseInfo',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=218,
  serialized_end=418,
)

_GLASSESCASEINFO.fields_by_name['errorCode'].enum_type = common__pb2._EERRORCODE
_GLASSESCASEDATAPACKAGE.fields_by_name['commandId'].enum_type = _EGLASSESCASECOMMANDID
_GLASSESCASEDATAPACKAGE.fields_by_name['caseInfo'].message_type = _GLASSESCASEINFO
_GLASSESCASEDATAPACKAGE.oneofs_by_name['_caseInfo'].fields.append(
  _GLASSESCASEDATAPACKAGE.fields_by_name['caseInfo'])
_GLASSESCASEDATAPACKAGE.fields_by_name['caseInfo'].containing_oneof = _GLASSESCASEDATAPACKAGE.oneofs_by_name['_caseInfo']
DESCRIPTOR.message_types_by_name['GlassesCaseInfo'] = _GLASSESCASEINFO
DESCRIPTOR.message_types_by_name['GlassesCaseDataPackage'] = _GLASSESCASEDATAPACKAGE
DESCRIPTOR.enum_types_by_name['eGlassesCaseCommandId'] = _EGLASSESCASECOMMANDID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GlassesCaseInfo = _reflection.GeneratedProtocolMessageType('GlassesCaseInfo', (_message.Message,), {
  'DESCRIPTOR' : _GLASSESCASEINFO,
  '__module__' : 'glasses_case_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.glasses_case.GlassesCaseInfo)
  })
_sym_db.RegisterMessage(GlassesCaseInfo)

GlassesCaseDataPackage = _reflection.GeneratedProtocolMessageType('GlassesCaseDataPackage', (_message.Message,), {
  'DESCRIPTOR' : _GLASSESCASEDATAPACKAGE,
  '__module__' : 'glasses_case_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.glasses_case.GlassesCaseDataPackage)
  })
_sym_db.RegisterMessage(GlassesCaseDataPackage)


# @@protoc_insertion_point(module_scope)
