# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logger.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='logger.proto',
  package='even_connect.g2.logger',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0clogger.proto\x12\x16\x65ven_connect.g2.logger\"\x84\x03\n\x13logger_main_msg_ctx\x12\x34\n\x03\x63md\x18\x01 \x01(\x0e\x32\'.even_connect.g2.logger.logger_Cmd_list\x12\x13\n\x0bmagicRandom\x18\x02 \x01(\x05\x12\x12\n\nbleTransEn\x18\x03 \x01(\x05\x12\x42\n\x08levelMsg\x18\x04 \x01(\x0b\x32+.even_connect.g2.logger.ble_trans_level_msgH\x00\x88\x01\x01\x12\x13\n\x06logStr\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x45\n\nrequestMsg\x18\x06 \x01(\x0b\x32,.even_connect.g2.logger.request_filelist_msgH\x02\x88\x01\x01\x12<\n\x06\x64\x65lMsg\x18\x07 \x01(\x0b\x32\'.even_connect.g2.logger.delete_file_msgH\x03\x88\x01\x01\x42\x0b\n\t_levelMsgB\t\n\x07_logStrB\r\n\x0b_requestMsgB\t\n\x07_delMsg\",\n\x13\x62le_trans_level_msg\x12\x15\n\rbleTransLevel\x18\x01 \x01(\x05\"5\n\x0f\x64\x65lete_file_msg\x12\x15\n\x08\x66ileName\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_fileName\"(\n\x14request_filelist_msg\x12\x10\n\x08\x66ileName\x18\x01 \x03(\t*\xc6\x01\n\x0flogger_Cmd_list\x12\x18\n\x14\x43ONNECT_HEART_PACKET\x10\x00\x12\x19\n\x15\x42LE_LOGGER_SWITCH_SET\x10\x01\x12\x18\n\x14\x42LE_LOGGER_LEVEL_SET\x10\x02\x12\x1b\n\x17\x44\x45VICE_SEND_LOGGER_DATA\x10\x03\x12\x15\n\x11REQUEST_FILE_NAME\x10\x04\x12\x14\n\x10\x44\x45LETE_FILE_NAME\x10\x05\x12\x1a\n\x16\x44\x45LETE_ALL_LOGGER_FILE\x10\x06\x62\x06proto3'
)

_LOGGER_CMD_LIST = _descriptor.EnumDescriptor(
  name='logger_Cmd_list',
  full_name='even_connect.g2.logger.logger_Cmd_list',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECT_HEART_PACKET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BLE_LOGGER_SWITCH_SET', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BLE_LOGGER_LEVEL_SET', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_SEND_LOGGER_DATA', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REQUEST_FILE_NAME', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DELETE_FILE_NAME', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DELETE_ALL_LOGGER_FILE', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=575,
  serialized_end=773,
)
_sym_db.RegisterEnumDescriptor(_LOGGER_CMD_LIST)

logger_Cmd_list = enum_type_wrapper.EnumTypeWrapper(_LOGGER_CMD_LIST)
CONNECT_HEART_PACKET = 0
BLE_LOGGER_SWITCH_SET = 1
BLE_LOGGER_LEVEL_SET = 2
DEVICE_SEND_LOGGER_DATA = 3
REQUEST_FILE_NAME = 4
DELETE_FILE_NAME = 5
DELETE_ALL_LOGGER_FILE = 6



_LOGGER_MAIN_MSG_CTX = _descriptor.Descriptor(
  name='logger_main_msg_ctx',
  full_name='even_connect.g2.logger.logger_main_msg_ctx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='even_connect.g2.logger.logger_main_msg_ctx.cmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='magicRandom', full_name='even_connect.g2.logger.logger_main_msg_ctx.magicRandom', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bleTransEn', full_name='even_connect.g2.logger.logger_main_msg_ctx.bleTransEn', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='levelMsg', full_name='even_connect.g2.logger.logger_main_msg_ctx.levelMsg', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='logStr', full_name='even_connect.g2.logger.logger_main_msg_ctx.logStr', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requestMsg', full_name='even_connect.g2.logger.logger_main_msg_ctx.requestMsg', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delMsg', full_name='even_connect.g2.logger.logger_main_msg_ctx.delMsg', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_levelMsg', full_name='even_connect.g2.logger.logger_main_msg_ctx._levelMsg',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_logStr', full_name='even_connect.g2.logger.logger_main_msg_ctx._logStr',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_requestMsg', full_name='even_connect.g2.logger.logger_main_msg_ctx._requestMsg',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_delMsg', full_name='even_connect.g2.logger.logger_main_msg_ctx._delMsg',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=41,
  serialized_end=429,
)


_BLE_TRANS_LEVEL_MSG = _descriptor.Descriptor(
  name='ble_trans_level_msg',
  full_name='even_connect.g2.logger.ble_trans_level_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bleTransLevel', full_name='even_connect.g2.logger.ble_trans_level_msg.bleTransLevel', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=475,
)


_DELETE_FILE_MSG = _descriptor.Descriptor(
  name='delete_file_msg',
  full_name='even_connect.g2.logger.delete_file_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileName', full_name='even_connect.g2.logger.delete_file_msg.fileName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_fileName', full_name='even_connect.g2.logger.delete_file_msg._fileName',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=477,
  serialized_end=530,
)


_REQUEST_FILELIST_MSG = _descriptor.Descriptor(
  name='request_filelist_msg',
  full_name='even_connect.g2.logger.request_filelist_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileName', full_name='even_connect.g2.logger.request_filelist_msg.fileName', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=572,
)

_LOGGER_MAIN_MSG_CTX.fields_by_name['cmd'].enum_type = _LOGGER_CMD_LIST
_LOGGER_MAIN_MSG_CTX.fields_by_name['levelMsg'].message_type = _BLE_TRANS_LEVEL_MSG
_LOGGER_MAIN_MSG_CTX.fields_by_name['requestMsg'].message_type = _REQUEST_FILELIST_MSG
_LOGGER_MAIN_MSG_CTX.fields_by_name['delMsg'].message_type = _DELETE_FILE_MSG
_LOGGER_MAIN_MSG_CTX.oneofs_by_name['_levelMsg'].fields.append(
  _LOGGER_MAIN_MSG_CTX.fields_by_name['levelMsg'])
_LOGGER_MAIN_MSG_CTX.fields_by_name['levelMsg'].containing_oneof = _LOGGER_MAIN_MSG_CTX.oneofs_by_name['_levelMsg']
_LOGGER_MAIN_MSG_CTX.oneofs_by_name['_logStr'].fields.append(
  _LOGGER_MAIN_MSG_CTX.fields_by_name['logStr'])
_LOGGER_MAIN_MSG_CTX.fields_by_name['logStr'].containing_oneof = _LOGGER_MAIN_MSG_CTX.oneofs_by_name['_logStr']
_LOGGER_MAIN_MSG_CTX.oneofs_by_name['_requestMsg'].fields.append(
  _LOGGER_MAIN_MSG_CTX.fields_by_name['requestMsg'])
_LOGGER_MAIN_MSG_CTX.fields_by_name['requestMsg'].containing_oneof = _LOGGER_MAIN_MSG_CTX.oneofs_by_name['_requestMsg']
_LOGGER_MAIN_MSG_CTX.oneofs_by_name['_delMsg'].fields.append(
  _LOGGER_MAIN_MSG_CTX.fields_by_name['delMsg'])
_LOGGER_MAIN_MSG_CTX.fields_by_name['delMsg'].containing_oneof = _LOGGER_MAIN_MSG_CTX.oneofs_by_name['_delMsg']
_DELETE_FILE_MSG.oneofs_by_name['_fileName'].fields.append(
  _DELETE_FILE_MSG.fields_by_name['fileName'])
_DELETE_FILE_MSG.fields_by_name['fileName'].containing_oneof = _DELETE_FILE_MSG.oneofs_by_name['_fileName']
DESCRIPTOR.message_types_by_name['logger_main_msg_ctx'] = _LOGGER_MAIN_MSG_CTX
DESCRIPTOR.message_types_by_name['ble_trans_level_msg'] = _BLE_TRANS_LEVEL_MSG
DESCRIPTOR.message_types_by_name['delete_file_msg'] = _DELETE_FILE_MSG
DESCRIPTOR.message_types_by_name['request_filelist_msg'] = _REQUEST_FILELIST_MSG
DESCRIPTOR.enum_types_by_name['logger_Cmd_list'] = _LOGGER_CMD_LIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

logger_main_msg_ctx = _reflection.GeneratedProtocolMessageType('logger_main_msg_ctx', (_message.Message,), {
  'DESCRIPTOR' : _LOGGER_MAIN_MSG_CTX,
  '__module__' : 'logger_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.logger.logger_main_msg_ctx)
  })
_sym_db.RegisterMessage(logger_main_msg_ctx)

ble_trans_level_msg = _reflection.GeneratedProtocolMessageType('ble_trans_level_msg', (_message.Message,), {
  'DESCRIPTOR' : _BLE_TRANS_LEVEL_MSG,
  '__module__' : 'logger_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.logger.ble_trans_level_msg)
  })
_sym_db.RegisterMessage(ble_trans_level_msg)

delete_file_msg = _reflection.GeneratedProtocolMessageType('delete_file_msg', (_message.Message,), {
  'DESCRIPTOR' : _DELETE_FILE_MSG,
  '__module__' : 'logger_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.logger.delete_file_msg)
  })
_sym_db.RegisterMessage(delete_file_msg)

request_filelist_msg = _reflection.GeneratedProtocolMessageType('request_filelist_msg', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST_FILELIST_MSG,
  '__module__' : 'logger_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.logger.request_filelist_msg)
  })
_sym_db.RegisterMessage(request_filelist_msg)


# @@protoc_insertion_point(module_scope)
