# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: module_configure.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='module_configure.proto',
  package='even_connect.g2.module_configure',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16module_configure.proto\x12 even_connect.g2.module_configure\"\xf2\x02\n\x1dmodule_configure_main_msg_ctx\x12H\n\x03\x63md\x18\x01 \x01(\x0e\x32;.even_connect.g2.module_configure.module_configure_Cmd_list\x12\x13\n\x0bmagicRandom\x18\x02 \x01(\x05\x12]\n\x11SysGeneralSetting\x18\x03 \x01(\x0b\x32=.even_connect.g2.module_configure.send_system_general_settingH\x00\x88\x01\x01\x12\x61\n\x17\x44\x61shboardGeneralSetting\x18\x04 \x01(\x0b\x32;.even_connect.g2.module_configure.dashboard_general_settingH\x01\x88\x01\x01\x42\x14\n\x12_SysGeneralSettingB\x1a\n\x18_DashboardGeneralSetting\"3\n\x19\x64\x61shboard_general_setting\x12\x16\n\x0e\x61utoCloseValue\x18\x01 \x01(\x05\"4\n\x1bsend_system_general_setting\x12\x15\n\rlanguageIndex\x18\x01 \x01(\x05*\x92\x01\n\x19module_configure_Cmd_list\x12!\n\x1dSYSTEM_GENERAL_SETTING_PACKET\x10\x00\x12*\n&APP_INQUIRE_DASHBOARD_AUTO_CLOSE_VALUE\x10\x01\x12&\n\"APP_SET_DASHBOARD_AUTO_CLOSE_VALUE\x10\x02\x62\x06proto3'
)

_MODULE_CONFIGURE_CMD_LIST = _descriptor.EnumDescriptor(
  name='module_configure_Cmd_list',
  full_name='even_connect.g2.module_configure.module_configure_Cmd_list',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SYSTEM_GENERAL_SETTING_PACKET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='APP_INQUIRE_DASHBOARD_AUTO_CLOSE_VALUE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='APP_SET_DASHBOARD_AUTO_CLOSE_VALUE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=541,
  serialized_end=687,
)
_sym_db.RegisterEnumDescriptor(_MODULE_CONFIGURE_CMD_LIST)

module_configure_Cmd_list = enum_type_wrapper.EnumTypeWrapper(_MODULE_CONFIGURE_CMD_LIST)
SYSTEM_GENERAL_SETTING_PACKET = 0
APP_INQUIRE_DASHBOARD_AUTO_CLOSE_VALUE = 1
APP_SET_DASHBOARD_AUTO_CLOSE_VALUE = 2



_MODULE_CONFIGURE_MAIN_MSG_CTX = _descriptor.Descriptor(
  name='module_configure_main_msg_ctx',
  full_name='even_connect.g2.module_configure.module_configure_main_msg_ctx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='even_connect.g2.module_configure.module_configure_main_msg_ctx.cmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='magicRandom', full_name='even_connect.g2.module_configure.module_configure_main_msg_ctx.magicRandom', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SysGeneralSetting', full_name='even_connect.g2.module_configure.module_configure_main_msg_ctx.SysGeneralSetting', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DashboardGeneralSetting', full_name='even_connect.g2.module_configure.module_configure_main_msg_ctx.DashboardGeneralSetting', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_SysGeneralSetting', full_name='even_connect.g2.module_configure.module_configure_main_msg_ctx._SysGeneralSetting',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_DashboardGeneralSetting', full_name='even_connect.g2.module_configure.module_configure_main_msg_ctx._DashboardGeneralSetting',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=61,
  serialized_end=431,
)


_DASHBOARD_GENERAL_SETTING = _descriptor.Descriptor(
  name='dashboard_general_setting',
  full_name='even_connect.g2.module_configure.dashboard_general_setting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='autoCloseValue', full_name='even_connect.g2.module_configure.dashboard_general_setting.autoCloseValue', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=484,
)


_SEND_SYSTEM_GENERAL_SETTING = _descriptor.Descriptor(
  name='send_system_general_setting',
  full_name='even_connect.g2.module_configure.send_system_general_setting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='languageIndex', full_name='even_connect.g2.module_configure.send_system_general_setting.languageIndex', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=486,
  serialized_end=538,
)

_MODULE_CONFIGURE_MAIN_MSG_CTX.fields_by_name['cmd'].enum_type = _MODULE_CONFIGURE_CMD_LIST
_MODULE_CONFIGURE_MAIN_MSG_CTX.fields_by_name['SysGeneralSetting'].message_type = _SEND_SYSTEM_GENERAL_SETTING
_MODULE_CONFIGURE_MAIN_MSG_CTX.fields_by_name['DashboardGeneralSetting'].message_type = _DASHBOARD_GENERAL_SETTING
_MODULE_CONFIGURE_MAIN_MSG_CTX.oneofs_by_name['_SysGeneralSetting'].fields.append(
  _MODULE_CONFIGURE_MAIN_MSG_CTX.fields_by_name['SysGeneralSetting'])
_MODULE_CONFIGURE_MAIN_MSG_CTX.fields_by_name['SysGeneralSetting'].containing_oneof = _MODULE_CONFIGURE_MAIN_MSG_CTX.oneofs_by_name['_SysGeneralSetting']
_MODULE_CONFIGURE_MAIN_MSG_CTX.oneofs_by_name['_DashboardGeneralSetting'].fields.append(
  _MODULE_CONFIGURE_MAIN_MSG_CTX.fields_by_name['DashboardGeneralSetting'])
_MODULE_CONFIGURE_MAIN_MSG_CTX.fields_by_name['DashboardGeneralSetting'].containing_oneof = _MODULE_CONFIGURE_MAIN_MSG_CTX.oneofs_by_name['_DashboardGeneralSetting']
DESCRIPTOR.message_types_by_name['module_configure_main_msg_ctx'] = _MODULE_CONFIGURE_MAIN_MSG_CTX
DESCRIPTOR.message_types_by_name['dashboard_general_setting'] = _DASHBOARD_GENERAL_SETTING
DESCRIPTOR.message_types_by_name['send_system_general_setting'] = _SEND_SYSTEM_GENERAL_SETTING
DESCRIPTOR.enum_types_by_name['module_configure_Cmd_list'] = _MODULE_CONFIGURE_CMD_LIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

module_configure_main_msg_ctx = _reflection.GeneratedProtocolMessageType('module_configure_main_msg_ctx', (_message.Message,), {
  'DESCRIPTOR' : _MODULE_CONFIGURE_MAIN_MSG_CTX,
  '__module__' : 'module_configure_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.module_configure.module_configure_main_msg_ctx)
  })
_sym_db.RegisterMessage(module_configure_main_msg_ctx)

dashboard_general_setting = _reflection.GeneratedProtocolMessageType('dashboard_general_setting', (_message.Message,), {
  'DESCRIPTOR' : _DASHBOARD_GENERAL_SETTING,
  '__module__' : 'module_configure_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.module_configure.dashboard_general_setting)
  })
_sym_db.RegisterMessage(dashboard_general_setting)

send_system_general_setting = _reflection.GeneratedProtocolMessageType('send_system_general_setting', (_message.Message,), {
  'DESCRIPTOR' : _SEND_SYSTEM_GENERAL_SETTING,
  '__module__' : 'module_configure_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.module_configure.send_system_general_setting)
  })
_sym_db.RegisterMessage(send_system_general_setting)


# @@protoc_insertion_point(module_scope)
