# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='notification.proto',
  package='even_connect.g2.notification',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12notification.proto\x12\x1c\x65ven_connect.g2.notification\x1a\x0c\x63ommon.proto\"l\n\x19NotificationWhitelistCtrl\x12\x18\n\x10whitelistDisable\x18\x01 \x01(\x05\x12\x35\n\terrorCode\x18\x02 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"\x95\x01\n\x13NotificationCommRsp\x12G\n\tcommandId\x18\x01 \x01(\x0e\x32\x34.even_connect.g2.notification.eNotificationCommandId\x12\x35\n\terrorCode\x18\x02 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"l\n\x0fNotificationIOS\x12\r\n\x05\x61ppID\x18\x01 \x01(\x0c\x12\x13\n\x0b\x64isplayName\x18\x02 \x01(\x0c\x12\x35\n\terrorCode\x18\x03 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"\xa7\x01\n\x13NotificationControl\x12\x13\n\x0bnotifEnable\x18\x01 \x01(\x05\x12\x16\n\x0e\x61utoDispEnable\x18\x02 \x01(\x05\x12\x10\n\x08\x64ispTime\x18\x03 \x01(\x05\x12\x35\n\terrorCode\x18\x04 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\x12\x1a\n\x12\x61voidDisturbEnable\x18\x05 \x01(\x05\"\xc5\x03\n\x17NotificationDataPackage\x12G\n\tcommandId\x18\x01 \x01(\x0e\x32\x34.even_connect.g2.notification.eNotificationCommandId\x12\x13\n\x0bmagicRandom\x18\x02 \x01(\x05\x12\x44\n\x04\x63trl\x18\x03 \x01(\x0b\x32\x31.even_connect.g2.notification.NotificationControlH\x00\x88\x01\x01\x12?\n\x03IOS\x18\x04 \x01(\x0b\x32-.even_connect.g2.notification.NotificationIOSH\x01\x88\x01\x01\x12\x44\n\x04resp\x18\x05 \x01(\x0b\x32\x31.even_connect.g2.notification.NotificationCommRspH\x02\x88\x01\x01\x12S\n\rwhitelistCtrl\x18\x06 \x01(\x0b\x32\x37.even_connect.g2.notification.NotificationWhitelistCtrlH\x03\x88\x01\x01\x42\x07\n\x05_ctrlB\x06\n\x04_IOSB\x07\n\x05_respB\x10\n\x0e_whitelistCtrl*\x94\x01\n\x16\x65NotificationCommandId\x12\x10\n\x0cNONE_COMMAND\x10\x00\x12\x15\n\x11NOTIFICATION_CTRL\x10\x01\x12\x14\n\x10NOTIFICATION_IOS\x10\x02\x12\x1f\n\x1bNOTIFICATION_WHITELIST_CTRL\x10\x03\x12\x1a\n\x15NOTIFICATION_COMM_RSP\x10\xa1\x01\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_ENOTIFICATIONCOMMANDID = _descriptor.EnumDescriptor(
  name='eNotificationCommandId',
  full_name='even_connect.g2.notification.eNotificationCommandId',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE_COMMAND', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOTIFICATION_CTRL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOTIFICATION_IOS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOTIFICATION_WHITELIST_CTRL', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOTIFICATION_COMM_RSP', index=4, number=161,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1065,
  serialized_end=1213,
)
_sym_db.RegisterEnumDescriptor(_ENOTIFICATIONCOMMANDID)

eNotificationCommandId = enum_type_wrapper.EnumTypeWrapper(_ENOTIFICATIONCOMMANDID)
NONE_COMMAND = 0
NOTIFICATION_CTRL = 1
NOTIFICATION_IOS = 2
NOTIFICATION_WHITELIST_CTRL = 3
NOTIFICATION_COMM_RSP = 161



_NOTIFICATIONWHITELISTCTRL = _descriptor.Descriptor(
  name='NotificationWhitelistCtrl',
  full_name='even_connect.g2.notification.NotificationWhitelistCtrl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='whitelistDisable', full_name='even_connect.g2.notification.NotificationWhitelistCtrl.whitelistDisable', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='even_connect.g2.notification.NotificationWhitelistCtrl.errorCode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=174,
)


_NOTIFICATIONCOMMRSP = _descriptor.Descriptor(
  name='NotificationCommRsp',
  full_name='even_connect.g2.notification.NotificationCommRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='commandId', full_name='even_connect.g2.notification.NotificationCommRsp.commandId', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='even_connect.g2.notification.NotificationCommRsp.errorCode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=326,
)


_NOTIFICATIONIOS = _descriptor.Descriptor(
  name='NotificationIOS',
  full_name='even_connect.g2.notification.NotificationIOS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='appID', full_name='even_connect.g2.notification.NotificationIOS.appID', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='displayName', full_name='even_connect.g2.notification.NotificationIOS.displayName', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='even_connect.g2.notification.NotificationIOS.errorCode', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=436,
)


_NOTIFICATIONCONTROL = _descriptor.Descriptor(
  name='NotificationControl',
  full_name='even_connect.g2.notification.NotificationControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='notifEnable', full_name='even_connect.g2.notification.NotificationControl.notifEnable', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='autoDispEnable', full_name='even_connect.g2.notification.NotificationControl.autoDispEnable', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dispTime', full_name='even_connect.g2.notification.NotificationControl.dispTime', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='even_connect.g2.notification.NotificationControl.errorCode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='avoidDisturbEnable', full_name='even_connect.g2.notification.NotificationControl.avoidDisturbEnable', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=606,
)


_NOTIFICATIONDATAPACKAGE = _descriptor.Descriptor(
  name='NotificationDataPackage',
  full_name='even_connect.g2.notification.NotificationDataPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='commandId', full_name='even_connect.g2.notification.NotificationDataPackage.commandId', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='magicRandom', full_name='even_connect.g2.notification.NotificationDataPackage.magicRandom', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ctrl', full_name='even_connect.g2.notification.NotificationDataPackage.ctrl', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='IOS', full_name='even_connect.g2.notification.NotificationDataPackage.IOS', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resp', full_name='even_connect.g2.notification.NotificationDataPackage.resp', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='whitelistCtrl', full_name='even_connect.g2.notification.NotificationDataPackage.whitelistCtrl', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_ctrl', full_name='even_connect.g2.notification.NotificationDataPackage._ctrl',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_IOS', full_name='even_connect.g2.notification.NotificationDataPackage._IOS',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_resp', full_name='even_connect.g2.notification.NotificationDataPackage._resp',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_whitelistCtrl', full_name='even_connect.g2.notification.NotificationDataPackage._whitelistCtrl',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=609,
  serialized_end=1062,
)

_NOTIFICATIONWHITELISTCTRL.fields_by_name['errorCode'].enum_type = common__pb2._EERRORCODE
_NOTIFICATIONCOMMRSP.fields_by_name['commandId'].enum_type = _ENOTIFICATIONCOMMANDID
_NOTIFICATIONCOMMRSP.fields_by_name['errorCode'].enum_type = common__pb2._EERRORCODE
_NOTIFICATIONIOS.fields_by_name['errorCode'].enum_type = common__pb2._EERRORCODE
_NOTIFICATIONCONTROL.fields_by_name['errorCode'].enum_type = common__pb2._EERRORCODE
_NOTIFICATIONDATAPACKAGE.fields_by_name['commandId'].enum_type = _ENOTIFICATIONCOMMANDID
_NOTIFICATIONDATAPACKAGE.fields_by_name['ctrl'].message_type = _NOTIFICATIONCONTROL
_NOTIFICATIONDATAPACKAGE.fields_by_name['IOS'].message_type = _NOTIFICATIONIOS
_NOTIFICATIONDATAPACKAGE.fields_by_name['resp'].message_type = _NOTIFICATIONCOMMRSP
_NOTIFICATIONDATAPACKAGE.fields_by_name['whitelistCtrl'].message_type = _NOTIFICATIONWHITELISTCTRL
_NOTIFICATIONDATAPACKAGE.oneofs_by_name['_ctrl'].fields.append(
  _NOTIFICATIONDATAPACKAGE.fields_by_name['ctrl'])
_NOTIFICATIONDATAPACKAGE.fields_by_name['ctrl'].containing_oneof = _NOTIFICATIONDATAPACKAGE.oneofs_by_name['_ctrl']
_NOTIFICATIONDATAPACKAGE.oneofs_by_name['_IOS'].fields.append(
  _NOTIFICATIONDATAPACKAGE.fields_by_name['IOS'])
_NOTIFICATIONDATAPACKAGE.fields_by_name['IOS'].containing_oneof = _NOTIFICATIONDATAPACKAGE.oneofs_by_name['_IOS']
_NOTIFICATIONDATAPACKAGE.oneofs_by_name['_resp'].fields.append(
  _NOTIFICATIONDATAPACKAGE.fields_by_name['resp'])
_NOTIFICATIONDATAPACKAGE.fields_by_name['resp'].containing_oneof = _NOTIFICATIONDATAPACKAGE.oneofs_by_name['_resp']
_NOTIFICATIONDATAPACKAGE.oneofs_by_name['_whitelistCtrl'].fields.append(
  _NOTIFICATIONDATAPACKAGE.fields_by_name['whitelistCtrl'])
_NOTIFICATIONDATAPACKAGE.fields_by_name['whitelistCtrl'].containing_oneof = _NOTIFICATIONDATAPACKAGE.oneofs_by_name['_whitelistCtrl']
DESCRIPTOR.message_types_by_name['NotificationWhitelistCtrl'] = _NOTIFICATIONWHITELISTCTRL
DESCRIPTOR.message_types_by_name['NotificationCommRsp'] = _NOTIFICATIONCOMMRSP
DESCRIPTOR.message_types_by_name['NotificationIOS'] = _NOTIFICATIONIOS
DESCRIPTOR.message_types_by_name['NotificationControl'] = _NOTIFICATIONCONTROL
DESCRIPTOR.message_types_by_name['NotificationDataPackage'] = _NOTIFICATIONDATAPACKAGE
DESCRIPTOR.enum_types_by_name['eNotificationCommandId'] = _ENOTIFICATIONCOMMANDID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotificationWhitelistCtrl = _reflection.GeneratedProtocolMessageType('NotificationWhitelistCtrl', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONWHITELISTCTRL,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.notification.NotificationWhitelistCtrl)
  })
_sym_db.RegisterMessage(NotificationWhitelistCtrl)

NotificationCommRsp = _reflection.GeneratedProtocolMessageType('NotificationCommRsp', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONCOMMRSP,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.notification.NotificationCommRsp)
  })
_sym_db.RegisterMessage(NotificationCommRsp)

NotificationIOS = _reflection.GeneratedProtocolMessageType('NotificationIOS', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONIOS,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.notification.NotificationIOS)
  })
_sym_db.RegisterMessage(NotificationIOS)

NotificationControl = _reflection.GeneratedProtocolMessageType('NotificationControl', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONCONTROL,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.notification.NotificationControl)
  })
_sym_db.RegisterMessage(NotificationControl)

NotificationDataPackage = _reflection.GeneratedProtocolMessageType('NotificationDataPackage', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONDATAPACKAGE,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.notification.NotificationDataPackage)
  })
_sym_db.RegisterMessage(NotificationDataPackage)


# @@protoc_insertion_point(module_scope)
