# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ring.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ring.proto',
  package='even_connect.g2.ring',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nring.proto\x12\x14\x65ven_connect.g2.ring\x1a\x0c\x63ommon.proto\"\xf6\x02\n\x0bRingRawData\x12\x0f\n\x07\x62\x61ttery\x18\x01 \x01(\x05\x12\x14\n\x0c\x63hargeStates\x18\x02 \x01(\x05\x12\n\n\x02hr\x18\x03 \x01(\x05\x12\x13\n\x0bhrTimestamp\x18\x04 \x01(\x05\x12\x0c\n\x04spo2\x18\x05 \x01(\x05\x12\x15\n\rspo2Timestamp\x18\x06 \x01(\x05\x12\x0b\n\x03hrv\x18\x07 \x01(\x05\x12\x14\n\x0chrvTimestamp\x18\x08 \x01(\x05\x12\x0c\n\x04temp\x18\t \x01(\x05\x12\x15\n\rtempTimestamp\x18\n \x01(\x05\x12\x0f\n\x07\x61\x63tKcal\x18\x0b \x01(\x05\x12\x18\n\x10\x61\x63tKcalTimestamp\x18\x0c \x01(\x05\x12\x0f\n\x07\x61llKcal\x18\r \x01(\x05\x12\x18\n\x10\x61llKcalTimestamp\x18\x0e \x01(\x05\x12\r\n\x05steps\x18\x0f \x01(\x05\x12\x16\n\x0estepsTimestamp\x18\x10 \x01(\x05\x12\x35\n\terrorCode\x18\x11 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"\x9a\x01\n\tRingEvent\x12\x0f\n\x07ringMac\x18\x01 \x01(\x0c\x12\x31\n\x07\x65ventId\x18\x02 \x01(\x0e\x32 .even_connect.g2.ring.eRingEvent\x12\x12\n\neventParam\x18\x03 \x01(\x05\x12\x35\n\terrorCode\x18\x04 \x01(\x0e\x32\".even_connect.g2.common.eErrorCode\"\xe3\x01\n\x0fRingDataPackage\x12\x37\n\tcommandId\x18\x01 \x01(\x0e\x32$.even_connect.g2.ring.eRingCommandId\x12\x13\n\x0bmagicRandom\x18\x02 \x01(\x05\x12\x33\n\x05\x65vent\x18\x03 \x01(\x0b\x32\x1f.even_connect.g2.ring.RingEventH\x00\x88\x01\x01\x12\x37\n\x07rawData\x18\x04 \x01(\x0b\x32!.even_connect.g2.ring.RingRawDataH\x01\x88\x01\x01\x42\x08\n\x06_eventB\n\n\x08_rawData*,\n\neRingEvent\x12\x11\n\rUNKNOWN_EVENT\x10\x00\x12\x0b\n\x07\x42LE_ADV\x10\x01*;\n\x0e\x65RingCommandId\x12\x10\n\x0cNONE_COMMAND\x10\x00\x12\t\n\x05\x45VENT\x10\x01\x12\x0c\n\x08RAW_DATA\x10\x02\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_ERINGEVENT = _descriptor.EnumDescriptor(
  name='eRingEvent',
  full_name='even_connect.g2.ring.eRingEvent',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_EVENT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BLE_ADV', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=814,
  serialized_end=858,
)
_sym_db.RegisterEnumDescriptor(_ERINGEVENT)

eRingEvent = enum_type_wrapper.EnumTypeWrapper(_ERINGEVENT)
_ERINGCOMMANDID = _descriptor.EnumDescriptor(
  name='eRingCommandId',
  full_name='even_connect.g2.ring.eRingCommandId',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE_COMMAND', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVENT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RAW_DATA', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=860,
  serialized_end=919,
)
_sym_db.RegisterEnumDescriptor(_ERINGCOMMANDID)

eRingCommandId = enum_type_wrapper.EnumTypeWrapper(_ERINGCOMMANDID)
UNKNOWN_EVENT = 0
BLE_ADV = 1
NONE_COMMAND = 0
EVENT = 1
RAW_DATA = 2



_RINGRAWDATA = _descriptor.Descriptor(
  name='RingRawData',
  full_name='even_connect.g2.ring.RingRawData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='battery', full_name='even_connect.g2.ring.RingRawData.battery', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chargeStates', full_name='even_connect.g2.ring.RingRawData.chargeStates', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hr', full_name='even_connect.g2.ring.RingRawData.hr', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hrTimestamp', full_name='even_connect.g2.ring.RingRawData.hrTimestamp', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spo2', full_name='even_connect.g2.ring.RingRawData.spo2', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spo2Timestamp', full_name='even_connect.g2.ring.RingRawData.spo2Timestamp', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hrv', full_name='even_connect.g2.ring.RingRawData.hrv', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hrvTimestamp', full_name='even_connect.g2.ring.RingRawData.hrvTimestamp', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temp', full_name='even_connect.g2.ring.RingRawData.temp', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tempTimestamp', full_name='even_connect.g2.ring.RingRawData.tempTimestamp', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actKcal', full_name='even_connect.g2.ring.RingRawData.actKcal', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actKcalTimestamp', full_name='even_connect.g2.ring.RingRawData.actKcalTimestamp', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allKcal', full_name='even_connect.g2.ring.RingRawData.allKcal', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allKcalTimestamp', full_name='even_connect.g2.ring.RingRawData.allKcalTimestamp', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steps', full_name='even_connect.g2.ring.RingRawData.steps', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stepsTimestamp', full_name='even_connect.g2.ring.RingRawData.stepsTimestamp', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='even_connect.g2.ring.RingRawData.errorCode', index=16,
      number=17, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=425,
)


_RINGEVENT = _descriptor.Descriptor(
  name='RingEvent',
  full_name='even_connect.g2.ring.RingEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ringMac', full_name='even_connect.g2.ring.RingEvent.ringMac', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eventId', full_name='even_connect.g2.ring.RingEvent.eventId', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eventParam', full_name='even_connect.g2.ring.RingEvent.eventParam', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='even_connect.g2.ring.RingEvent.errorCode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=582,
)


_RINGDATAPACKAGE = _descriptor.Descriptor(
  name='RingDataPackage',
  full_name='even_connect.g2.ring.RingDataPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='commandId', full_name='even_connect.g2.ring.RingDataPackage.commandId', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='magicRandom', full_name='even_connect.g2.ring.RingDataPackage.magicRandom', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event', full_name='even_connect.g2.ring.RingDataPackage.event', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rawData', full_name='even_connect.g2.ring.RingDataPackage.rawData', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_event', full_name='even_connect.g2.ring.RingDataPackage._event',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_rawData', full_name='even_connect.g2.ring.RingDataPackage._rawData',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=585,
  serialized_end=812,
)

_RINGRAWDATA.fields_by_name['errorCode'].enum_type = common__pb2._EERRORCODE
_RINGEVENT.fields_by_name['eventId'].enum_type = _ERINGEVENT
_RINGEVENT.fields_by_name['errorCode'].enum_type = common__pb2._EERRORCODE
_RINGDATAPACKAGE.fields_by_name['commandId'].enum_type = _ERINGCOMMANDID
_RINGDATAPACKAGE.fields_by_name['event'].message_type = _RINGEVENT
_RINGDATAPACKAGE.fields_by_name['rawData'].message_type = _RINGRAWDATA
_RINGDATAPACKAGE.oneofs_by_name['_event'].fields.append(
  _RINGDATAPACKAGE.fields_by_name['event'])
_RINGDATAPACKAGE.fields_by_name['event'].containing_oneof = _RINGDATAPACKAGE.oneofs_by_name['_event']
_RINGDATAPACKAGE.oneofs_by_name['_rawData'].fields.append(
  _RINGDATAPACKAGE.fields_by_name['rawData'])
_RINGDATAPACKAGE.fields_by_name['rawData'].containing_oneof = _RINGDATAPACKAGE.oneofs_by_name['_rawData']
DESCRIPTOR.message_types_by_name['RingRawData'] = _RINGRAWDATA
DESCRIPTOR.message_types_by_name['RingEvent'] = _RINGEVENT
DESCRIPTOR.message_types_by_name['RingDataPackage'] = _RINGDATAPACKAGE
DESCRIPTOR.enum_types_by_name['eRingEvent'] = _ERINGEVENT
DESCRIPTOR.enum_types_by_name['eRingCommandId'] = _ERINGCOMMANDID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RingRawData = _reflection.GeneratedProtocolMessageType('RingRawData', (_message.Message,), {
  'DESCRIPTOR' : _RINGRAWDATA,
  '__module__' : 'ring_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.ring.RingRawData)
  })
_sym_db.RegisterMessage(RingRawData)

RingEvent = _reflection.GeneratedProtocolMessageType('RingEvent', (_message.Message,), {
  'DESCRIPTOR' : _RINGEVENT,
  '__module__' : 'ring_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.ring.RingEvent)
  })
_sym_db.RegisterMessage(RingEvent)

RingDataPackage = _reflection.GeneratedProtocolMessageType('RingDataPackage', (_message.Message,), {
  'DESCRIPTOR' : _RINGDATAPACKAGE,
  '__module__' : 'ring_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.ring.RingDataPackage)
  })
_sym_db.RegisterMessage(RingDataPackage)


# @@protoc_insertion_point(module_scope)
