# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_id_def.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_id_def.proto',
  package='even_connect.g2.service_id_def',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14service_id_def.proto\x12\x1e\x65ven_connect.g2.service_id_def*\xbe\x07\n\x03SID\x12\x15\n\x11UI_DEFAULT_APP_ID\x10\x00\x12\"\n\x1eUI_BACKGROUND_DASHBOARD_APP_ID\x10\x01\x12\x19\n\x15UI_FOREGROUND_MEUN_ID\x10\x03\x12!\n\x1dUI_FOREGROUND_NOTIFICATION_ID\x10\x04\x12\x17\n\x13UI_TRANSLATE_APP_ID\x10\x05\x12\x18\n\x14UI_TELEPROMPT_APP_ID\x10\x06\x12\x1c\n\x18UI_FOREGROUND_EVEN_AI_ID\x10\x07\x12\x1f\n\x1bUI_BACKGROUND_NAVIGATION_ID\x10\x08\x12\x15\n\x11UI_SETTING_APP_ID\x10\t\x12\x18\n\x14UI_TRANSCRIBE_APP_ID\x10\n\x12\x18\n\x14UI_CONVERSATE_APP_ID\x10\x0b\x12\x17\n\x13UI_QUICKLIST_APP_ID\x10\x0c\x12\x1c\n\x18SERVICE_SYNC_INFO_APP_ID\x10\r\x12\x14\n\x10UI_HEALTH_APP_ID\x10\x0e\x12\x14\n\x10UI_LOGGER_APP_ID\x10\x0f\x12\x18\n\x14UI_ONBOARDING_APP_ID\x10\x10\x12#\n\x1fSERVICE_MODULE_CONFIGURE_APP_ID\x10 \x12%\n!UI_FOREGROUND_SYSTEM_ALERT_APP_ID\x10!\x12\x1e\n\x19UX_DEVICE_SETTINGS_APP_ID\x10\x80\x01\x12\x1b\n\x16UX_GLASSES_CASE_APP_ID\x10\x81\x01\x12\x18\n\x13UX_RING_ROW_DATA_ID\x10\x90\x01\x12\x1a\n\x15UX_RING_DATA_RELAY_ID\x10\x91\x01\x12\x1b\n\x16UX_OTA_TRANSMIT_CMD_ID\x10\xc0\x01\x12 \n\x1bUX_OTA_TRANSMIT_RAW_DATA_ID\x10\xc1\x01\x12\x1e\n\x19UX_OTA_EXPORT_FILE_CMD_ID\x10\xc2\x01\x12#\n\x1eUX_OTA_EXPORT_FILE_RAW_DATA_ID\x10\xc3\x01\x12%\n UX_EVEN_FILE_SERVICE_CMD_SEND_ID\x10\xc4\x01\x12*\n%UX_EVEN_FILE_SERVICE_RAW_SEND_DATA_ID\x10\xc5\x01\x12\'\n\"UX_EVEN_FILE_SERVICE_CMD_EXPORT_ID\x10\xc6\x01\x12,\n\'UX_EVEN_FILE_SERVICE_RAW_EXPORT_DATA_ID\x10\xc7\x01\x12\x17\n\x12INVALID_SERVICE_ID\x10\xff\x01\x62\x06proto3'
)

_SID = _descriptor.EnumDescriptor(
  name='SID',
  full_name='even_connect.g2.service_id_def.SID',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UI_DEFAULT_APP_ID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UI_BACKGROUND_DASHBOARD_APP_ID', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UI_FOREGROUND_MEUN_ID', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UI_FOREGROUND_NOTIFICATION_ID', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UI_TRANSLATE_APP_ID', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UI_TELEPROMPT_APP_ID', index=5, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UI_FOREGROUND_EVEN_AI_ID', index=6, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UI_BACKGROUND_NAVIGATION_ID', index=7, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UI_SETTING_APP_ID', index=8, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UI_TRANSCRIBE_APP_ID', index=9, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UI_CONVERSATE_APP_ID', index=10, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UI_QUICKLIST_APP_ID', index=11, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SERVICE_SYNC_INFO_APP_ID', index=12, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UI_HEALTH_APP_ID', index=13, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UI_LOGGER_APP_ID', index=14, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UI_ONBOARDING_APP_ID', index=15, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SERVICE_MODULE_CONFIGURE_APP_ID', index=16, number=32,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UI_FOREGROUND_SYSTEM_ALERT_APP_ID', index=17, number=33,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UX_DEVICE_SETTINGS_APP_ID', index=18, number=128,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UX_GLASSES_CASE_APP_ID', index=19, number=129,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UX_RING_ROW_DATA_ID', index=20, number=144,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UX_RING_DATA_RELAY_ID', index=21, number=145,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UX_OTA_TRANSMIT_CMD_ID', index=22, number=192,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UX_OTA_TRANSMIT_RAW_DATA_ID', index=23, number=193,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UX_OTA_EXPORT_FILE_CMD_ID', index=24, number=194,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UX_OTA_EXPORT_FILE_RAW_DATA_ID', index=25, number=195,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UX_EVEN_FILE_SERVICE_CMD_SEND_ID', index=26, number=196,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UX_EVEN_FILE_SERVICE_RAW_SEND_DATA_ID', index=27, number=197,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UX_EVEN_FILE_SERVICE_CMD_EXPORT_ID', index=28, number=198,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UX_EVEN_FILE_SERVICE_RAW_EXPORT_DATA_ID', index=29, number=199,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INVALID_SERVICE_ID', index=30, number=255,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=57,
  serialized_end=1015,
)
_sym_db.RegisterEnumDescriptor(_SID)

SID = enum_type_wrapper.EnumTypeWrapper(_SID)
UI_DEFAULT_APP_ID = 0
UI_BACKGROUND_DASHBOARD_APP_ID = 1
UI_FOREGROUND_MEUN_ID = 3
UI_FOREGROUND_NOTIFICATION_ID = 4
UI_TRANSLATE_APP_ID = 5
UI_TELEPROMPT_APP_ID = 6
UI_FOREGROUND_EVEN_AI_ID = 7
UI_BACKGROUND_NAVIGATION_ID = 8
UI_SETTING_APP_ID = 9
UI_TRANSCRIBE_APP_ID = 10
UI_CONVERSATE_APP_ID = 11
UI_QUICKLIST_APP_ID = 12
SERVICE_SYNC_INFO_APP_ID = 13
UI_HEALTH_APP_ID = 14
UI_LOGGER_APP_ID = 15
UI_ONBOARDING_APP_ID = 16
SERVICE_MODULE_CONFIGURE_APP_ID = 32
UI_FOREGROUND_SYSTEM_ALERT_APP_ID = 33
UX_DEVICE_SETTINGS_APP_ID = 128
UX_GLASSES_CASE_APP_ID = 129
UX_RING_ROW_DATA_ID = 144
UX_RING_DATA_RELAY_ID = 145
UX_OTA_TRANSMIT_CMD_ID = 192
UX_OTA_TRANSMIT_RAW_DATA_ID = 193
UX_OTA_EXPORT_FILE_CMD_ID = 194
UX_OTA_EXPORT_FILE_RAW_DATA_ID = 195
UX_EVEN_FILE_SERVICE_CMD_SEND_ID = 196
UX_EVEN_FILE_SERVICE_RAW_SEND_DATA_ID = 197
UX_EVEN_FILE_SERVICE_CMD_EXPORT_ID = 198
UX_EVEN_FILE_SERVICE_RAW_EXPORT_DATA_ID = 199
INVALID_SERVICE_ID = 255


DESCRIPTOR.enum_types_by_name['SID'] = _SID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
