# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sync_info.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sync_info.proto',
  package='even_connect.g2.sync_info',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fsync_info.proto\x12\x19\x65ven_connect.g2.sync_info\"\xbe\x01\n\x16sync_info_main_msg_ctx\x12>\n\x07\x63mdList\x18\x01 \x01(\x0e\x32-.even_connect.g2.sync_info.Sync_Info_Cmd_list\x12\x13\n\x0bmagicRandom\x18\x02 \x01(\x05\x12\x43\n\x07\x64\x61taMsg\x18\x03 \x01(\x0b\x32-.even_connect.g2.sync_info.sync_info_data_msgH\x00\x88\x01\x01\x42\n\n\x08_dataMsg\"F\n\x12sync_info_data_msg\x12\x17\n\x0f\x62\x61\x63kgroundAppID\x18\x01 \x01(\x05\x12\x17\n\x0f\x66oregroundAppID\x18\x02 \x01(\x05*H\n\x12Sync_Info_Cmd_list\x12\x19\n\x15\x41PP_REQUEST_SYNC_INFO\x10\x00\x12\x17\n\x13OS_NOTIFY_SYNC_INFO\x10\x01\x62\x06proto3'
)

_SYNC_INFO_CMD_LIST = _descriptor.EnumDescriptor(
  name='Sync_Info_Cmd_list',
  full_name='even_connect.g2.sync_info.Sync_Info_Cmd_list',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='APP_REQUEST_SYNC_INFO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OS_NOTIFY_SYNC_INFO', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=311,
  serialized_end=383,
)
_sym_db.RegisterEnumDescriptor(_SYNC_INFO_CMD_LIST)

Sync_Info_Cmd_list = enum_type_wrapper.EnumTypeWrapper(_SYNC_INFO_CMD_LIST)
APP_REQUEST_SYNC_INFO = 0
OS_NOTIFY_SYNC_INFO = 1



_SYNC_INFO_MAIN_MSG_CTX = _descriptor.Descriptor(
  name='sync_info_main_msg_ctx',
  full_name='even_connect.g2.sync_info.sync_info_main_msg_ctx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmdList', full_name='even_connect.g2.sync_info.sync_info_main_msg_ctx.cmdList', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='magicRandom', full_name='even_connect.g2.sync_info.sync_info_main_msg_ctx.magicRandom', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataMsg', full_name='even_connect.g2.sync_info.sync_info_main_msg_ctx.dataMsg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_dataMsg', full_name='even_connect.g2.sync_info.sync_info_main_msg_ctx._dataMsg',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=47,
  serialized_end=237,
)


_SYNC_INFO_DATA_MSG = _descriptor.Descriptor(
  name='sync_info_data_msg',
  full_name='even_connect.g2.sync_info.sync_info_data_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='backgroundAppID', full_name='even_connect.g2.sync_info.sync_info_data_msg.backgroundAppID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='foregroundAppID', full_name='even_connect.g2.sync_info.sync_info_data_msg.foregroundAppID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=309,
)

_SYNC_INFO_MAIN_MSG_CTX.fields_by_name['cmdList'].enum_type = _SYNC_INFO_CMD_LIST
_SYNC_INFO_MAIN_MSG_CTX.fields_by_name['dataMsg'].message_type = _SYNC_INFO_DATA_MSG
_SYNC_INFO_MAIN_MSG_CTX.oneofs_by_name['_dataMsg'].fields.append(
  _SYNC_INFO_MAIN_MSG_CTX.fields_by_name['dataMsg'])
_SYNC_INFO_MAIN_MSG_CTX.fields_by_name['dataMsg'].containing_oneof = _SYNC_INFO_MAIN_MSG_CTX.oneofs_by_name['_dataMsg']
DESCRIPTOR.message_types_by_name['sync_info_main_msg_ctx'] = _SYNC_INFO_MAIN_MSG_CTX
DESCRIPTOR.message_types_by_name['sync_info_data_msg'] = _SYNC_INFO_DATA_MSG
DESCRIPTOR.enum_types_by_name['Sync_Info_Cmd_list'] = _SYNC_INFO_CMD_LIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

sync_info_main_msg_ctx = _reflection.GeneratedProtocolMessageType('sync_info_main_msg_ctx', (_message.Message,), {
  'DESCRIPTOR' : _SYNC_INFO_MAIN_MSG_CTX,
  '__module__' : 'sync_info_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.sync_info.sync_info_main_msg_ctx)
  })
_sym_db.RegisterMessage(sync_info_main_msg_ctx)

sync_info_data_msg = _reflection.GeneratedProtocolMessageType('sync_info_data_msg', (_message.Message,), {
  'DESCRIPTOR' : _SYNC_INFO_DATA_MSG,
  '__module__' : 'sync_info_pb2'
  # @@protoc_insertion_point(class_scope:even_connect.g2.sync_info.sync_info_data_msg)
  })
_sym_db.RegisterMessage(sync_info_data_msg)


# @@protoc_insertion_point(module_scope)
